CREATE TABLE VEICULOS (
	ID INTEGER NOT NULL IDENTITY,
	NOME VARCHAR(100) NOT NULL,
	MARCA VARCHAR(100) NOT NULL,
	MODELO VARCHAR(100) NOT NULL,
	FABRICACAO DATE NOT NULL,
	CONSUMOCIDADE DECIMAL(100,2) NOT NULL,
	CONSUMORODOVIA DECIMAL(100,2) NOT NULL,
	CONSTRAINT VEICULOS_PK PRIMARY KEY (ID)
);
